http:
  port: "8081"

american:
  host: "training4-american-api.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  client_id: "d846d01ea59640108779eaaa532d00ca"
  client_secret: "F7C5ecA48EBA449399b4B140416849B0"
  
united:
  host: "ilt.learn.mulesoft.com"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  
delta:
  wsdl: "http://ilt.learn.mulesoft.com/delta?wsdl"